apiVersion: v1
kind: Service
metadata:
 name: clustersvc
spec:
 type: ClusterIP
 ports:
 - targetPort: 80 #port of container
   port: 5000 #port for accessing with clusterIP                                                                                          
 selector:
  app: webrs
