apiVersion: v1
kind: Pod
metadata:
 name: config-pod
spec:
 containers:
 - name: config
   image: quay.io/gauravkumar9130/nginxdemo
   volumeMounts:
   - name: config-vol
     mountPath: /data
 volumes:
 - name: config-vol
   configMap:
    name: app-config
