apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: portdbpolicy
spec:
 podSelector:
  matchLabels:
   app: db
 policyTypes:
 - Ingress
 ingress:
 - from:
   - podSelector:
      matchLabels:
       app: web
   ports:
   - protocol: TCP
     port: 3306 
