apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment-example
spec:
 replicas: 5
 selector:
  matchLabels:
   app: prodv1
 template:
  metadata:
   labels:
    app: prodv1
  spec:
   containers:
   - name: web
     image: quay.io/gauravkumar9130/production:v1
