apiVersion: v1
kind: Pod
metadata:
 name: pod-emptydir
spec:
 containers:
 - name: emptydir
   image: quay.io/gauravkumar9130/nginxdemo
   volumeMounts:
   - name: temporary
     mountPath: /raju
 volumes:
 - name: temporary
   emptyDir: {}
