apiVersion: v1
kind: Service
metadata:
 name: greenservice
spec:
 type: ClusterIP
 ports:
 - targetPort: 80 #port of container
   port: 80 #port for accessing with clusterIP
 selector:
  vesrion: green
