apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: hotel-ingress
 annotations: #similar to label and not used for filtering
  kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: "jalluapp.com"
   http:
    paths:
    - path: /
      pathType: Prefix
      backend:
       service:
        name: hotel
        port:
         number: 80
    - path: /tea       
      pathType: Prefix
      backend:      
       service:     
        name: tea
        port:       
         number: 80
    - path: /coffee       
      pathType: Prefix
      backend:      
       service:     
        name: coffee 
        port:       
         number: 80
