apiVersion: v1
kind: Pod
metadata:
 name: worker1-pod-taint
spec:
 containers:
 - name: c1
   image: quay.io/gauravkumar9130/mywebapp
 tolerations:
 - key: "app"
   operator: "Equal"
   value: "tester"
   effect: "NoSchedule"
