apiVersion: v1
kind: Pod
metadata:
 name: nodeaffinity-pod
spec:
 containers:
 - name: c1
   image: quay.io/gauravkumar9130/mywebapp
 affinity:
  nodeAffinity:
   requiredDuringSchedulingrequiredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: "size"
        operator: "In"
        values:
        - "medium"
