apiVersion: v1
kind: Pod
metadata:
 name: pod-securitycontext
spec: 
 containers:
 - name: c1
   image: quay.io/gauravkumar9130/nginxdemo
   securityContext:
    capabilities:
     add: ["NET_RAW"]  

