apiVersion: v1
kind: Pod
metadata:
 name: pod-pvc
spec:
 containers:
 - name: c1
   image: quay.io/gauravkumar9130/nginxdemo
   volumeMounts:
   - name: myvol
     mountPath: /mycontainerdata
 volumes:
 - name: myvol
   persistentVolumeClaim:
    claimName: pvc1
