apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv1
spec:
 storageClassName: host
 accessModes:
 #ReadWriteOnce - only one node can do readwrite
 #ReadWriteMany - multiple nodes can do readwrite
 #ReadOnlyMany - read only volume
 - ReadWriteMany
 capacity:
  storage: 2Gi
 hostPath:
  path: /myvoldata
