apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: rs-example
spec:
 replicas: 2
 selector: #condition for selector
  matchExpressions:
  - key: dep
    operator: In
    values:
    - set1
    - set2
 template:
  metadata:
   name: web
   labels:
    dep: set1
  spec:
   containers: 
   - name: c1
     image: quay.io/gauravkumar9130/mywebapp
