apiVersion: v1
kind: Pod
metadata: 
 name: worker2-web
spec:
 containers:
 - name: c1
   image: quay.io/gauravkumar9130/mywebapp
 tolerations:
 - key: "web"
   operator: "Equal"
   value: "tester"
   effect: "NoSchedule" 
